"""fsd

Revision ID: a9afc1853926
Revises: f36ce8eac083
Create Date: 2021-04-16 20:27:44.557812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9afc1853926'
down_revision = 'f36ce8eac083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.String(length=256), nullable=True, comment='用户请求唯一key，路由上用'))
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户名，没啥用',
               existing_nullable=True)
    op.drop_index('user_name', table_name='user')
    op.create_unique_constraint(None, 'user', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('user_name', 'user', ['user_name'], unique=True)
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='用户名，没啥用',
               existing_nullable=True)
    op.drop_column('user', 'key')
    # ### end Alembic commands ###
